### ISSUE TITLE
lolfixer removes ambients unnecessarily if they exceed 16MB

### ISSUE THREAD

**Issue by agb1** [omni-axa/Lolfixer#1]
Instead of 

            INNER_PATCH_FILE ~%resref%.wav~ BEGIN
              SET "exists" = 1
            END

Maybe use FILE_EXISTS_IN_GAME instead?  I'm not sure if that side-steps WeiDU's size limit for opening a file.  If not, maybe SIZE_OF_FILE.

**Comment by burner1024** [comment]
lolfixer does use FILE_EXISTS_IN_GAME. I don't see the code that you quoted at all.

**Comment by agb1** [comment]
It seems the BiG World Fixpack distributes an (old) copy of Lolfixer instead of getting this one.

**Comment by burner1024** [comment]
I guess you can use git submodule instead of mirroring the files manually
